[project]
name = "backend"
version = "0.1.0"
description = "Hotel Ordering Platform Backend Core"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "django>=5.0.0",
    "django-ninja>=1.1.0",
    "psycopg[binary]>=3.1.0",
    "django-cors-headers>=4.0.0",
    "pyjwt>=2.8.0",
    "gunicorn>=21.2.0",
    "uvicorn[standard]>=0.29.0",
    "celery>=5.3.0",
    "redis>=5.0.0",
    "whitenoise>=6.12.0",
    "reportlab>=5.0.1",
    "email-validator>=2.3.0",
]

[tool.uv]
package = false

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
