# Generated by Django 6.0.5 on 2026-08-21 07:04

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('place', models.CharField(blank=True, max_length=200)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('cuisine', models.CharField(blank=True, max_length=80)),
                ('banner_image', models.URLField(blank=True)),
                ('gallery_images', models.JSONField(blank=True, default=list)),
                ('google_map_url', models.URLField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('opening_time', models.TimeField(default=datetime.time(8, 0))),
                ('closing_time', models.TimeField(default=datetime.time(22, 0))),
                ('is_online', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('rejection_reason', models.TextField(blank=True)),
                ('has_delivery', models.BooleanField(default=True)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('flat_delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('delivery_radius_km', models.FloatField(default=10)),
                ('avg_delivery_minutes', models.PositiveIntegerField(default=35)),
                ('slot_morning', models.BooleanField(default=True)),
                ('slot_afternoon', models.BooleanField(default=True)),
                ('slot_evening', models.BooleanField(default=True)),
                ('rating', models.FloatField(default=0)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-rating', 'name'],
            },
        ),
    ]
